# Generated by Django 5.0.4 on 2024-04-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
